====== WebDriver manager ======
Current google-chrome version is 99.0.4844
Get LATEST chromedriver version for 99.0.4844 google-chrome
Driver [/home/alexzuzow/.wdm/drivers/chromedriver/linux64/99.0.4844.51/chromedriver] found in cache
141.52206598909078 141.32057471642065
(25, 36)
Score:  16
step time: 0.5531981169988285
(25, 36)
Score:  16
step time: 0.5466744440018374
(25, 36)
/home/alexzuzow/Desktop/agar_multiagent/utils.py:182: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  value =torch.nn.functional.softmax(classifier(digits[i]).squeeze(0))
Score:  16
step time: 0.5432536889966286
(25, 36)
Score:  16
step time: 0.5698757170030149
(25, 36)
Score:  16
step time: 0.5600711400002183
(25, 36)
Score:  16
step time: 0.6270145119997323
(25, 36)
Score:  16
step time: 0.5312752069985436
(25, 36)
Score:  16
step time: 0.5199262460009777
(25, 36)
Score:  17
step time: 0.6134252480005671
(25, 36)
Score:  17
step time: 0.5691848269998445
(25, 36)
Score:  17
step time: 0.5482281990007323
(25, 36)
Score:  17
step time: 0.5693384669975785
(25, 36)
Score:  17
step time: 0.5690635559985822
(25, 36)
Score:  17
step time: 0.5736245150001196
(25, 36)
Score:  19
step time: 0.5229045310006768
(25, 36)
Score:  19
step time: 0.53504733400041
(25, 36)
Score:  20
step time: 0.5618829330014705
(25, 36)
Score:  20
step time: 0.5557801819995802
(25, 36)
Score:  20
step time: 0.6440020549998735
(25, 36)
Score:  20
step time: 0.587557670998649
(25, 36)
====== WebDriver manager ======
Current google-chrome version is 99.0.4844
Get LATEST chromedriver version for 99.0.4844 google-chrome
Driver [/home/alexzuzow/.wdm/drivers/chromedriver/linux64/99.0.4844.51/chromedriver] found in cache
Score:  20
step time: 0.6047362220015202
(25, 36)
Score:  0
step time: 0.5723813330005214
(25, 36)
Score:  0
step time: 0.45485350700255367
====== WebDriver manager ======
Current google-chrome version is 99.0.4844
Get LATEST chromedriver version for 99.0.4844 google-chrome
Driver [/home/alexzuzow/.wdm/drivers/chromedriver/linux64/99.0.4844.51/chromedriver] found in cache
Message: chrome not reachable
  (Session info: chrome=99.0.4844.74)
Stacktrace:
#0 0x55af68e987d3 <unknown>
#1 0x55af68bf451f <unknown>
#2 0x55af68be2954 <unknown>
#3 0x55af68be3369 <unknown>
#4 0x55af68be5132 <unknown>
#5 0x55af68bdd486 <unknown>
#6 0x55af68bf5a82 <unknown>
#7 0x55af68c5b118 <unknown>
#8 0x55af68c485a3 <unknown>
#9 0x55af68c1dddc <unknown>
#10 0x55af68c1ede5 <unknown>
#11 0x55af68ec949d <unknown>
#12 0x55af68ee260c <unknown>
#13 0x55af68ecb205 <unknown>
#14 0x55af68ee2ee5 <unknown>
#15 0x55af68ebf070 <unknown>
#16 0x55af68efe488 <unknown>
#17 0x55af68efe60c <unknown>
#18 0x55af68f17c6d <unknown>
#19 0x7f0b5dff5609 <unknown>
Traceback (most recent call last):
  File "/home/alexzuzow/Desktop/agar_multiagent/agar.py", line 62, in reset
    menu = WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH,'//*[@id="nick"]')))
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 78, in until
    value = method(self._driver)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 326, in _predicate
    target = driver.find_element(*target)  # grab element at locator
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=99.0.4844.74)
Stacktrace:
#0 0x55af68e987d3 <unknown>
#1 0x55af68bf451f <unknown>
#2 0x55af68be2954 <unknown>
#3 0x55af68be3369 <unknown>
#4 0x55af68be5132 <unknown>
#5 0x55af68bdd486 <unknown>
#6 0x55af68bf5a82 <unknown>
#7 0x55af68c5b118 <unknown>
#8 0x55af68c485a3 <unknown>
#9 0x55af68c1dddc <unknown>
#10 0x55af68c1ede5 <unknown>
#11 0x55af68ec949d <unknown>
#12 0x55af68ee260c <unknown>
#13 0x55af68ecb205 <unknown>
#14 0x55af68ee2ee5 <unknown>
#15 0x55af68ebf070 <unknown>
#16 0x55af68efe488 <unknown>
#17 0x55af68efe60c <unknown>
#18 0x55af68f17c6d <unknown>
#19 0x7f0b5dff5609 <unknown>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/alexzuzow/Desktop/agar_multiagent/train_DQN.py", line 126, in <module>
    state = agar1.reset()
  File "/home/alexzuzow/Desktop/agar_multiagent/agar.py", line 90, in reset
    self.reset()
  File "/home/alexzuzow/Desktop/agar_multiagent/agar.py", line 62, in reset
    menu = WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH,'//*[@id="nick"]')))
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 86, in until
    time.sleep(self._poll)
KeyboardInterrupt