2022-04-19 04:32:38,925 INFO    MainThread:15419 [wandb_setup.py:_flush():75] Loading settings from /home/alexzuzow/.config/wandb/settings
2022-04-19 04:32:38,925 INFO    MainThread:15419 [wandb_setup.py:_flush():75] Loading settings from /home/alexzuzow/Desktop/agar_multiagent/wandb/settings
2022-04-19 04:32:38,925 INFO    MainThread:15419 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-19 04:32:38,925 INFO    MainThread:15419 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'train_DQN.py', 'program': '/home/alexzuzow/Desktop/agar_multiagent/train_DQN.py'}
2022-04-19 04:32:38,925 INFO    MainThread:15419 [wandb_init.py:_log_setup():438] Logging user logs to /home/alexzuzow/Desktop/agar_multiagent/wandb/run-20220419_043238-1ztlslkz/logs/debug.log
2022-04-19 04:32:38,926 INFO    MainThread:15419 [wandb_init.py:_log_setup():439] Logging internal logs to /home/alexzuzow/Desktop/agar_multiagent/wandb/run-20220419_043238-1ztlslkz/logs/debug-internal.log
2022-04-19 04:32:38,926 INFO    MainThread:15419 [wandb_init.py:init():472] calling init triggers
2022-04-19 04:32:38,926 INFO    MainThread:15419 [wandb_init.py:init():475] wandb.init called with sweep_config: {}
config: {}
2022-04-19 04:32:38,926 INFO    MainThread:15419 [wandb_init.py:init():525] starting backend
2022-04-19 04:32:38,926 INFO    MainThread:15419 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-19 04:32:38,944 INFO    MainThread:15419 [backend.py:ensure_launched():219] starting backend process...
2022-04-19 04:32:38,958 INFO    MainThread:15419 [backend.py:ensure_launched():224] started backend process with pid: 15432
2022-04-19 04:32:38,959 INFO    MainThread:15419 [wandb_init.py:init():534] backend started and connected
2022-04-19 04:32:38,965 INFO    MainThread:15419 [wandb_init.py:init():598] updated telemetry
2022-04-19 04:32:38,999 INFO    MainThread:15419 [wandb_init.py:init():629] communicating run to backend with 30 second timeout
2022-04-19 04:32:39,574 INFO    MainThread:15419 [wandb_run.py:_on_init():1922] communicating current version
2022-04-19 04:32:39,633 INFO    MainThread:15419 [wandb_run.py:_on_init():1926] got version response 
2022-04-19 04:32:39,633 INFO    MainThread:15419 [wandb_init.py:init():660] starting run threads in backend
2022-04-19 04:32:41,175 WARNING MainThread:15419 [wandb_init.py:init():1017] interrupted
Traceback (most recent call last):
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 996, in init
    run = wi.init()
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 671, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 221, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 439, in _communicate_run_start
    result = self._communicate(rec)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 225, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
